server:
  port: 8090
  servlet:
    context-path: /
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.56.109:3306/dbBoard?allowMultiQueries=true
    hikari:
      username: root
      password: root

  mail:
    host: smtp.gmail.com
    port: 587
    username: yueonsu@gmail.com
    password: phwlmdncgurtqjro
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.yueonsu

